import Head from 'next/head';
import styles from '@/styles/Home.module.scss';
import TodoForm from '@/components/molecules/TodoForm';
import TodoContextsProvider from '@/contexts/TodoContexts';
import TodoList from '@/components/organisms/TodoList';

export default function Home() {
  return (
    <>
      <Head>
        <title>Next Todo Sample</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <h1>Todo App</h1>
        <TodoContextsProvider>
          <TodoForm />
          <TodoList />
        </TodoContextsProvider>
      </div>
    </>
  );
}
